name: Bug Issue
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What is the bug, what is the unexpected behavior?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: what-is-expectet
    attributes:
      label: What is expected?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you want to see!
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output (If any)
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell