blank_issues_enabled: false
contact_links:
  - name: Flexbooks Kanban Board
    url: https://github.com/orgs/FlexBooks/projects/1
    about: View all Issues
  - name: Flexbooks Home
    url: https://github.com/FlexBooks
    about: Flexbooks Home